### ISSUE TITLE
Instructions Not Clear

### ISSUE THREAD

**Issue by ElliottBott** [FlaUI/FlaUInspect#12]
Please Update the readme.md to include information that you can get this lovely tool through Chocolatey, I spent literal hours trying to download this and compile on my own only to realise I somehow skipped .NET 4.7.1 and couldn't install it and tried to compile it myself. I Even looked at Cake and so on. It'd be a literal godsend to future users if you could add this little bit of information.

Install Chocolatey here using your Windows Powershell:
https://chocolatey.org/install

Then in cmd or Power shell do:
"choco install flauinspect"

can be run in cmd by just typing:
"flauinspect"

or by going to the chocolatey install folder and locating the .exe there.

**Comment by Roemer** [comment]
There is already a link to chocolatey in the readmy and the "releases" here on github contains the latest release as precompiled zip. But I added a small chapter for installation :)
