### ISSUE TITLE
Handle some runtime exceptions which appear during interaction with Telerik WPF based apps

### ISSUE THREAD

**Issue by aurax** [FlaUI/FlaUInspect#13]
Two exceptions were observed:

1) <FlaUInspect>\src\FlaUInspect\Core\HoverMode.cs, line 43:
var hoveredElement = _automation.FromPoint(screenPos);
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
```

2) <FlaUInspect>\src\FlaUInspect\ViewModels\ElementViewModel.cs, line 298:
var foreColor = (int)pattern.DocumentRange.GetAttributeValue(TextAttributes.ForegroundColor);
```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=FlaUInspect
  StackTrace:
   at FlaUInspect.ViewModels.ElementViewModel.LoadDetails() in <FlaUInspect>\src\FlaUInspect\ViewModels\ElementViewModel.cs:line 298
```

**Comment by aurax** [comment]
I've made a fix for it.

**Comment by Roemer** [comment]
I now even made a better handling for the textpattern details.
