### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by thachvv** [FlaUI/FlaUInspect#16]
When i run code with visual, it show some error:

Error	CS0104	'AutomationElement' is an ambiguous reference between 'System.Windows.Automation.AutomationElement' and 'FlaUI.Core.AutomationElements.AutomationElement'	FlaUInspect	D:\XXX\FlaUInspect-master\FlaUInspect-master\src\FlaUInspect\ViewModels\ElementViewModel.cs	23

Error	CS0104	'ControlType' is an ambiguous reference between 'System.Windows.Automation.ControlType' and 'FlaUI.Core.Definitions.ControlType'	FlaUInspect	D:\XXX\FlaUInspect-master\FlaUInspect-master\src\FlaUInspect\ViewModels\ElementViewModel.cs	81

I don't know exactly where reference

**Comment by Roemer** [comment]
Are you using visual studio 2019? Make sure to not include System.Windows.Automation in the `using` at the top. It works fine here and on the ci.
